### ISSUE TITLE
Websockets connection is inconsistent

### ISSUE THREAD

**Issue by drshrey** [codeamp/panel#185]
**Describe the bug**
The websockets connection will return `400 BAD REQUEST` errors at times. We should have a consistently working WS connection in order to keep developers up to date on high traffic pages like Releases without them having to refresh the page.

**To Reproduce**
1. Go to the index page for codeamp. 
2. Open inspector and look at console.
3. You should see a websocket error message that looks something like `WebSocket connection to <URL> failed: Error during WebSocket handshake: Unexpected response: 400.`

**Expected behavior**
There should be no errors for websocket connections on any of the client side pages.

**Screenshots**
![websocketerr](https://user-images.githubusercontent.com/3188413/42351370-84daa45a-8069-11e8-878b-7ecddc2684fa.png)

**Desktop (please complete the following information):**
 - Chrome Browser

**Comment by aballman** [comment]
This isn't a problem with the codebase itself. It is a problem with AWS ELBs and how they handle proxy protocol. I have adjusted our elb's to enable proxy protocol and setup the ports to forward on a SSL/TCP connection to enable HTTP or WSS connections.

There is presently an issue with the dev setup as the containers keep getting marked as unhealthy and removed from the load balancer.

Since this isn't a problem with CodeAmp itself I'm going to close this one. Particularly since it is working in production presently. I am also actively taking a look at the dev issue (kind of hard to do since the error condition isn't sustained) so that one should be resolved shortly as well.
