### ISSUE TITLE
Handling 403 Forbidden for Auth

### ISSUE THREAD

**Issue by drshrey** [codeamp/panel#196]
**Describe the bug**
Now that we're sending 403s for invalid tokens, we should handle redirects to logins given the status code as opposed to checking a string value.

**To Reproduce**
Unsure but it happens for some users and not for others

**Expected behavior**
Should redirect you to login rather than cause a redirect loop or show an internal server page like it does now

**Desktop (please complete the following information):**
 - Chrome Browser

**Additional context**
- Perhaps the inconsistency between users has to do with dex cache?

**Comment by aballman** [comment]
I'm going to close this now as I don't think this is the 'graphql' way of handling things. Instead of returning a 403 if a user is unauthorized, we should return an 'error' construct in a 200 response.

Additionally, we ended up removing the 403 return so there is nothing outstanding to clean up after.
